version: '3.8'

services:
  db:
    image: postgres:15
    container_name: blog-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
    volumes:
      - blog-db-data:/var/lib/postgresql/data

  app:
    build: .
    image: blog-app:1.0
    container_name: blog-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/blogdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: admin
    depends_on:
      - db

volumes:
  blog-db-data: